## vim専用 LSP・補完プラグイン

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
  function! s:lsp_scroll_or_default(amount, fallback_key) abort
    if exists('*lsp#scroll')
      let lsp_key = lsp#scroll(a:amount)
      if type(lsp_key) == v:t_string && lsp_key !=# ''
        return lsp_key
      endif
    endif
    return a:fallback_key
  endfunction

  function! s:on_lsp_buffer_enabled() abort
    setlocal omnifunc=lsp#complete
    setlocal signcolumn=yes
    if exists('+tagfunc') | setlocal tagfunc=lsp#tagfunc | endif
    nmap <buffer> gd <plug>(lsp-definition)
    nmap <buffer> gs <plug>(lsp-document-symbol-search)
    nmap <buffer> gS <plug>(lsp-workspace-symbol-search)
    nmap <buffer> gr <plug>(lsp-references)
    nmap <buffer> gi <plug>(lsp-implementation)
    nmap <buffer> gt <plug>(lsp-type-definition)
    nmap <buffer> <leader>rn <plug>(lsp-rename)
    nmap <buffer> [g <plug>(lsp-previous-diagnostic)
    nmap <buffer> ]g <plug>(lsp-next-diagnostic)
    nmap <buffer> K <plug>(lsp-hover)
    nnoremap <buffer><expr> <C-f> <SID>lsp_scroll_or_default(+4, "\<C-f>")
    nnoremap <buffer><expr> <C-b> <SID>lsp_scroll_or_default(-4, "\<C-b>")

    let g:lsp_format_sync_timeout = 1000
    autocmd! BufWritePre *.ts,*.tsx,*.js,*.jsx,*.vue call execute('LspDocumentFormatSync')
  endfunction

  augroup lsp_install
    au!
    autocmd User lsp_buffer_enabled call s:on_lsp_buffer_enabled()
  augroup END
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['prabirshrestha/vim-lsp']

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'
hook_add = '''
  let g:asyncomplete_auto_popup = 1
  let g:asyncomplete_auto_completeopt = 0
  let g:asyncomplete_popup_delay = 200
  set completeopt=menuone,noinsert,noselect,preview
  
  " Tab で補完選択
  inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
  inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
  inoremap <expr> <cr>    pumvisible() ? asyncomplete#close_popup() : "\<cr>"
'''

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'
depends = ['prabirshrestha/asyncomplete.vim', 'prabirshrestha/vim-lsp']
